config/routes.rb
Rails.application.routes.draw do
  root 'weather#index', to: 'weather#index', as: 'weather_index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
require 'net/http'
require 'json'
class WeatherController < ApplicationController
  def index
    if params[:city].present?
      coordinates = Geocoder.coordinates(params[:city])
      if coordinates.present?
        url = "https://api.openweathermap.org/data/3.0/onecall?lat=#{coordinates[0]}&lon=#{coordinates[1]}&exclude={part}&appid=c68ee2d7664c5a19c544c5a3c7aa9e16"
        uri = URI(url)
        response = Net::HTTP.get(uri)
        @weather = JSON.parse(response)
      else
        @error = 'It seems this city does not exist. Please try again.'
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/LemireM"><i class="fab fa-github"></i></a>
    <a href="https://www.linkedin.com/in/mael-lemire-058aa62a4/"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
  made by myself :D
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmallWeatherApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  </head>

  <body>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/weather/index.html.erb
<div class="container">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1596627008830-41d373a44a96?q=80&w=2832&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
    <h1 class='title'>Welcome to Small Weather App!</h1>
    <p>search for a city to get its weather forecast</p>
  </div>
    <%= form_tag(weather_index_path, method: :get, class: "search-form") do %>
      <%= text_field_tag :city, params[:city], class: "search-input" %>
      <%= submit_tag "Search", class: "search-button" %>
    <% end %>
    <% if @weather.present? && @weather['current'].present? %>
      <div class="weather-info">
        <h2 class="city-name"><%= params[:city] %></h2>
        <p class="temperature">Temperature: <%= (@weather['current']['temp'] - 273.15).round %>ºC</p>
        <p class="humidity">Humidity: <%= @weather['current']['humidity'] %>%</p>
        <p class="description">Description: <%= @weather['current']['weather'].first['description'] %></p>
      </div>
    <% elsif @error %>
      <p class="error-message"><%= @error %></p>
    <% end %>
</div>